version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # ✅ Common Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./zacsgutters-api/.env # ✅ Default environment file
