version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # ✅ Already using multi-stage build!
    volumes:
      - .:/app  # ✅ Hot reload enabled
    environment:
      NODE_ENV: development  # ✅ No need for `target: development` in Dockerfile
